### ISSUE TITLE
hass-gs-alarm is not recording violation logs

### ISSUE THREAD

**Issue by Gaio-Christiano** [hostcc/hass-gs-alarm#23]
My G90B alarm triggers in zones that have been violated and the time is not reported in Home Assistant and I don't know how to have a record of the day and time of violation of the zones.

**Comment by hostcc** [comment]
@Gaio-Christiano , would you mind adding some details please, so that I guide you on a fix?
* Do you have the alarm panel changing the state to `Triggered` when alarm fires?
* Do you see corresponding event in integration event: `Settings` -> `Devices & Services` -> `Golden Security Alarm` -> `gs_alarm` (or whatever name it has in your setup) -> Logbook?
* Any errors/exceptions logged in HASS logs (`Settings` -> `System` -> `Logs`, we are looking for anything related to `pyg90alarm` or `gs_alarm`)
* Do you have your alarm panel configured with IP 10.10.10.250 on your WiFi network (https://github.com/hostcc/hass-gs-alarm?tab=readme-ov-file#description)? That'd make a difference if the integration uses events from panel or does polling instead

Just in case it'd be influential - what is the model/firmware of your device? You could look that up in `Device Info` section of the device (`Settings` -> `Devices & Services` -> `Golden Security Alarm` -> `gs_alarm`, or whatever name it has in your setup)?

**Comment by Gaio-Christiano** [comment]
Does the alarm panel change the Triggered state when the alarm goes off?

Yes, it does;

Do you see the corresponding event in the integration event: Settings-> Devices & Services-> Golden Security Alarm-> gs_alarm (or whatever name it has in your configuration) -> Logbook?

No, I don't, I can only see it in the Android mobile app "Ennio Security 2.0";

Any errors/exceptions recorded in the HASS logs (Settings-> System-> Logs, we are looking for anything related to pyg90alarm or gs_alarm)
I didn't find the HACS log;

Do you have your alarm panel configured with IP 10.10.10.250 on your WiFi network ( https://github.com/hostcc/hass-gs-alarm?tab=readme-ov-file#description )? It would make a difference if the integration used dashboard events or polling instead.
No, it has a fixed IP on my local network which is 192.168.0.33 so my network is 192.168.0.0;

Just in case it's important - what is the model/firmware of your device? Can you look this up in the Device Info section of the device (Settings->Devices & Services->Golden Security Alarm->gs_alarm, or whatever it's called in your configuration)?
For Golden Security it's 0.0.0 and for TSV018-C3SIA it's Firmware: MCU: 207, WiFi: 207

**Comment by hostcc** [comment]
Interesting thanks @Gaio-Christiano ! I use mine with 10.10.10.250 IP address so it delivers notifications to HASS instead of polling (as in your case). I'll try to simulate and see if anything is broken in that scenario.

**Comment by Gaio-Christiano** [comment]
In my opinion, it would communicate with any IP it receives from the local network.

In this time period I had several door openings, zones that had alarm triggers and no triggers were registered in Home Assistant.
So I don't know what's wrong or if there is a script to make the records.
![Captura de Tela (406)](https://github.com/user-attachments/assets/31d52ef7-5eb6-4d0c-9957-157f1e966be2)
![Captura de Tela (405)](https://github.com/user-attachments/assets/e3e54a06-4d5b-432f-ada5-5f9ca8e9e038)
![Captura de Tela (404)](https://github.com/user-attachments/assets/1e3c81f2-a377-4732-a87f-3906ee6f5555)
![Captura de Tela (403)](https://github.com/user-attachments/assets/b09be79e-1c81-48cf-94ce-647af9569c9e)
![Captura de Tela (402)](https://github.com/user-attachments/assets/9466ad0c-8555-4fcd-8f8f-1cf2708661b9)
![Captura de Tela (401)](https://github.com/user-attachments/assets/aee7efa6-f7e9-403b-90e8-be60de1c3d1f)
![Captura de Tela (400)](https://github.com/user-attachments/assets/e2432a83-a3b3-4092-9360-4bb46dc9768f)
![Captura de Tela (399)](https://github.com/user-attachments/assets/c3e99424-1d9f-4f5c-822a-8db3ad85fc95)

**Comment by hostcc** [comment]
@Gaio-Christiano , I've looked over the details captured during initial implementation - unfortunately, without notifications from the device no changes to sensors' state will be reflected. Simply put, sensors will always remain in inactive state (doors always closed etc.) and no details will be available when alarm fires (e.g. there will be no information on what sensor triggered that). Unfortunately, that is the limitation of the device and its firmware - I found no method of polling for sensor state, those are only delivered via notifications the device sends.

Additional side effect of the limitation above - changes in panel's state are reflected with somewhat a minute delay (basically, HomeAssistant's refresh interval for sensors). It means the alarm will only be noticed by HomeAssistant in a minute or so, though naturally most of us would stop it sooner, hence the HomeAssistant won't even notice the condition.

This limitation is mentioned in the https://github.com/hostcc/hass-gs-alarm/blob/master/README.md, along with `10.10.10.250` IP address trick. It might be possible that panel still sends the notifications even if configured for another address, though my experimentation didn't confirm that - to verify you'd need to ensure the HomeAssistant could receive broadcast network packets from the panel. That means no intermediate routers between those two, including a Docker network except `host` one. 

For my setup I just decided to change my WiFi address and had panel set to `10.10.10.250`. Depending on your network setup it might be possible to add another segment (typically via a VLAN) with above subnet and configure DHCP reservation for the panel. However, that'd be an advanced scenario, since you'll have to expose HomeAssistant to such additional segment as well, which highly depends on how your HomeAssistant setup looks like.

**Comment by hostcc** [comment]
@Gaio-Christiano , also, I'd check if door open/close alerts are enabled in mobile application - options screen, `Alarm Alert` (at least that is how it is named in `Carener 2` application I'm using). Potentially those might have a positive effect.

**Comment by Gaio-Christiano** [comment]
Yes, in the mobile application, as previously reported, everything works OK and shows me the trigger records in up to 50 records, if I remember correctly.
Now in Home Assistant, it does not record any trigger records and only records activation and deactivation records.

**Comment by hostcc** [comment]
@Gaio-Christiano , I have positive news - I've released [1.14.1](https://github.com/hostcc/hass-gs-alarm/releases/tag/1.14.1) version that supports simulating device alerts from history. It helps to workaround inability to receive device alerts via network broadcasts or device not having `10.10.10.250` IP Address.

Just update the integration, enable `Simulate device alerts from history` in the device configuration in Home Assistant (`Settings` -> `Devices & Services` -> `Golden Security Alarm` -> `gs_alarm` (or whatever it is named in your setup) -> `Configure`), and enable alerts of interest in mobile application.

Please see more details in the [documentation](https://github.com/hostcc/hass-gs-alarm/tree/master#:~:text=NOTE%20To%20work,to%20be%20sent)

I'd be very interested to hear on results, please

**Comment by Gaio-Christiano** [comment]
Good afternoon!
It's still the same, it doesn't record the date and time of the trigger or inform where it heard the trigger, it only records the information when it is triggered or deactivated.
Only in the mobile application is this information recorded in only 100 records.
![WhatsApp Image 2024-08-19 at 14 13 00](https://github.com/user-attachments/assets/eb5047f7-1247-46c8-b3b9-e9dd1e4ecad8)
![WhatsApp Image 2024-08-19 at 14 12 59 (3)](https://github.com/user-attachments/assets/933143fa-17a0-4113-b542-57f5ea4579cf)
![WhatsApp Image 2024-08-19 at 14 12 59 (2)](https://github.com/user-attachments/assets/36884145-1f4b-449f-a35d-7171c78f9a8f)
![WhatsApp Image 2024-08-19 at 14 12 59 (1)](https://github.com/user-attachments/assets/fa47ea13-be0f-4413-a829-558e73ab6571)
![WhatsApp Image 2024-08-19 at 14 12 59](https://github.com/user-attachments/assets/841a23ce-d5dd-406b-a9ad-9369c1b6bc35)
![WhatsApp Image 2024-08-19 at 14 12 58 (2)](https://github.com/user-attachments/assets/c3138026-7601-4e85-b385-63a044a3a712)
![WhatsApp Image 2024-08-19 at 14 12 58 (1)](https://github.com/user-attachments/assets/d060d211-b204-4796-9921-2f9540c86864)
![WhatsApp Image 2024-08-19 at 14 12 58](https://github.com/user-attachments/assets/51e66380-bdf9-4cf4-aaea-2558ab5619d0)
![30](https://github.com/user-attachments/assets/e2eba3f9-b54d-45c5-ba75-d821a69551f3)
![29](https://github.com/user-attachments/assets/9bbe790e-9545-443b-b6a8-445c7f933766)
![28](https://github.com/user-attachments/assets/3af88d71-53b7-4159-a0fd-3d6e131c8cce)
![27](https://github.com/user-attachments/assets/2bf992ea-70dd-497e-bfc5-0cc1862078ee)
![26](https://github.com/user-attachments/assets/c8acf0cd-283f-4054-a548-134370e2a0fe)
![25](https://github.com/user-attachments/assets/176d8a00-eafe-40b8-b4e0-4f94988ec8bd)
![24](https://github.com/user-attachments/assets/52038e72-19f9-4759-aaab-fc3b53cb9e52)
![23](https://github.com/user-attachments/assets/31a2ff8a-909e-4115-b3e6-fa7d4089de70)
![22](https://github.com/user-attachments/assets/ab5ec3f6-e3f6-4925-944b-9fcaf1ebe6db)
![21](https://github.com/user-attachments/assets/c41d9e52-f1a6-4a92-9998-0bc8c6a13279)
![20](https://github.com/user-attachments/assets/c4a31cd9-7afc-40fe-abd6-c0fedc63fdb3)

**Comment by Gaio-Christiano** [comment]
Yes, I enabled it and it's still the same, I updated it but the version appears to me as 0.0.0
![Sem título](https://github.com/user-attachments/assets/4557c1c7-78fd-49b8-9cff-3cf89a5003b1)

**Comment by hostcc** [comment]
> Yes, I enabled it and it's still the same, I updated it but the version appears to me as 0.0.0 ![Sem título](https://private-user-images.githubusercontent.com/57502464/359595632-4557c1c7-78fd-49b8-9cff-3cf89a5003b1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODIwMDUsIm5iZiI6MTcyNDE4MTcwNSwicGF0aCI6Ii81NzUwMjQ2NC8zNTk1OTU2MzItNDU1N2MxYzctNzhmZC00OWI4LTljZmYtM2NmODlhNTAwM2IxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE5MjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMmZmMjFkZTc0OWUyYTAxZjdmMzcwMGQyYTQyNGQ0MTBmNzQ4NWRhN2IwZjc5YjA1NTBhY2Y0YjMwZGYwOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8GIrKP4EkPK_-_eYZ6z46pVnYoT8u3AT6uapjdmAXMU)

Thanks, @Gaio-Christiano - `0.0.0` is fine (I have not yet updated it for a current one).
Did you enable relevant alerts in mobile application, like `door close` or `door open`? Alarms if triggered should be logger anyways, but without those settings door sensors' activity won't be reflected.

Finally, any errors you might see in `Settings` -> `System` -> `Logs` -> `Load full logs`, related to `gs_alarm` or `pyg90alarm`, please?

**Comment by Gaio-Christiano** [comment]
No, I didn't set up those closed and open door things.
It was all automatic.
3 errors appeared in the log and I'm loading them
![01](https://github.com/user-attachments/assets/71b8519b-a25e-4252-aff5-44fa8e981f9a)
![02](https://github.com/user-attachments/assets/fd9636ca-75e7-4cf0-8528-5e842234c800)
![03](https://github.com/user-attachments/assets/3f8aab84-10ab-4845-96ef-2867319eca07)
![WhatsApp Image 2024-08-20 at 19 40 28 (1)](https://github.com/user-attachments/assets/a5928638-86eb-4378-9694-52b7f7b0fac2)
![WhatsApp Image 2024-08-20 at 19 40 28](https://github.com/user-attachments/assets/1d969d3d-9221-4829-b39c-b125de95ec44)
![WhatsApp Image 2024-08-20 at 19 40 29 (1)](https://github.com/user-attachments/assets/b0df522d-f195-4c15-b7df-43201c380454)
![WhatsApp Image 2024-08-20 at 19 40 29](https://github.com/user-attachments/assets/fde64665-a2bf-4dc2-a0a3-513394e1c80a)

**Comment by hostcc** [comment]
@Gaio-Christiano , sorry for not being clear - I was speaking re: alert types enabled for the panel, not sensor.

This is how it looks in my mobile app (the screen below is activated by swiping right from the central one):

![IMG_1064](https://github.com/user-attachments/assets/4def07c0-918e-4caa-b69e-8f5b4aa953c9)

And then alert configuration:
![IMG_1065](https://github.com/user-attachments/assets/cf5661e7-6dfe-4cdd-b655-b7c0f79f6ec1)

**Comment by Gaio-Christiano** [comment]
good morning!
This part on my cell phone is all marked and I only use the G90B in WiFi mode, it has no GSM chip or 4g

**Comment by hostcc** [comment]
Thanks, @Gaio-Christiano ! If you'd update to version 1.15.1 or later it adds support for diagnostic information - you should be able to do that via `Download diagnostics` on device page. Once completed would be great if you'd attach the resulting file here - it has all sensitive information removed (such as sensor names and alike), so it should be safe to share.

**Comment by Gaio-Christiano** [comment]
aí está meu arquivo de log gerado pelo registro foi do dia 22/08/2024 para o dia de hoje 23/08/2024.

Continuo sem ter os registros de disparos das zonas

[home-assistant_gs_alarm_2024-08-23T12-52-58.614Z.zip](https://github.com/user-attachments/files/16728967/home-assistant_gs_alarm_2024-08-23T12-52-58.614Z.zip)

**Comment by Gaio-Christiano** [comment]
Good morning!
I'm sorry, I sent it in my native language

Here is my log file generated by the registry from 08/22/2024 to today 08/23/2024.

I still don't have the zone trigger records

**Comment by hostcc** [comment]
> Good morning! I'm sorry, I sent it in my native language
> 
> Here is my log file generated by the registry from 08/22/2024 to today 08/23/2024.
> 
> I still don't have the zone trigger records

Absolutely no worries, @Gaio-Christiano ! The log is very useful, though it is system log with debuglevel (not diagnostic information for the alarm panel), hence it contains non-redacted data - please remove the attachment from the issue, just in case.

**Comment by Gaio-Christiano** [comment]
I hope the log helps to find the fault and improve the system.
I have already removed the sent log.

**Comment by hostcc** [comment]
@Gaio-Christiano , I've reviewed the log you've provided and found the component functioned as expected - it properly generated changes to alarm panel in HomeAssistant. For example:

Panel was armed away:
```
2024-08-22 20:13:15.097 DEBUG (MainThread) [custom_components.gs_alarm.alarm_control_panel] Received arm/disarm callback: 1
```

Panel triggered alarm from sensor `xxx 04 movimento (I've obfuscated the real sensor name):
```
2024-08-23 09:52:21.316 DEBUG (MainThread) [custom_components.gs_alarm.alarm_control_panel] Received alarm callback: xxx 04 movimento (idx=103), entity id: binary_sensor.xxx_04_movimento
```

The `Received ... callback` message is logged right where the component tells HomeAssistant the panel's state has changed.

There were no door open/close alerts in the history, so sensor changes weren't generated.

To understand why panel didn't send those, could you please do `Download diagnostics` this time, please?

![image](https://github.com/user-attachments/assets/de6c1181-494d-430e-b5ac-1005cdebfe6a)

**Comment by Gaio-Christiano** [comment]
![20](https://github.com/user-attachments/assets/5a995c9b-d0f4-4e99-9021-a7fb518ab1eb)
[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-GA1801A9Y000941-c8b87053876ff397e496baf23b8244ad.json](https://github.com/user-attachments/files/16754236/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-GA1801A9Y000941-c8b87053876ff397e496baf23b8244ad.json)
[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-90d54eab916ea6fd693fc043d85c741c.json](https://github.com/user-attachments/files/16754238/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-90d54eab916ea6fd693fc043d85c741c.json)
[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-e28cd862c08838895d9d29f209971d65.json](https://github.com/user-attachments/files/16754239/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-e28cd862c08838895d9d29f209971d65.json)

Estão aí

**Comment by Gaio-Christiano** [comment]
![20](https://github.com/user-attachments/assets/e2aed7a1-b68d-44cc-825d-e7834eecb032)
[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-GA1801A9Y000941-c8b87053876ff397e496baf23b8244ad.json](https://github.com/user-attachments/files/16754243/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-GA1801A9Y000941-c8b87053876ff397e496baf23b8244ad.json)
[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-90d54eab916ea6fd693fc043d85c741c.json](https://github.com/user-attachments/files/16754244/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-90d54eab916ea6fd693fc043d85c741c.json)
[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-e28cd862c08838895d9d29f209971d65.json](https://github.com/user-attachments/files/16754246/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-e28cd862c08838895d9d29f209971d65.json)

Estão aí

**Comment by Gaio-Christiano** [comment]
![20](https://github.com/user-attachments/assets/dae5ebf6-7660-492a-8b56-946b31f9fcb3)


[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-GA1801A9Y000941-c8b87053876ff397e496baf23b8244ad.json](https://github.com/user-attachments/files/16754256/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-GA1801A9Y000941-c8b87053876ff397e496baf23b8244ad.json)



[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-90d54eab916ea6fd693fc043d85c741c.json](https://github.com/user-attachments/files/16754258/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-90d54eab916ea6fd693fc043d85c741c.json)



[gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-e28cd862c08838895d9d29f209971d65.json](https://github.com/user-attachments/files/16754261/gs_alarm-01J3MTR2EM9RDCWPN6YABXJX61-gs_alarm_GA1801A9Y000941-e28cd862c08838895d9d29f209971d65.json)



Estão aí

**Comment by Gaio-Christiano** [comment]
Good afternoon!
I changed the IP of my network and things got worse, where Home Assistant can no longer connect to the G90B alarm
![30](https://github.com/user-attachments/assets/2b9647a5-b759-4107-a6d2-3579b262da4f)
![31](https://github.com/user-attachments/assets/d51f29ef-0253-4f2b-959f-2075157a333a)
![32](https://github.com/user-attachments/assets/fc027530-f0f4-47dd-ab71-8e2fdc4467ad)
![33](https://github.com/user-attachments/assets/3d7c244c-0dc3-4728-be73-529e964d299e)
![34](https://github.com/user-attachments/assets/152bab62-2c73-4343-ad96-d330572d1c03)

**Comment by Gaio-Christiano** [comment]
eu coloquei o MAC dele no DHCP Address Reservation e reservei o IP 10.10.10.250 para o alarme G90B e agora ele não é reconhecido no home assistant e ele fica lento no celular

**Comment by Gaio-Christiano** [comment]
I returned Home Assistant and the G90B alarm to the old network with IP 192.168.0.0 and it started working again.
In the new network that I created with IP 10.10.10.0 it did not work in Home Assistant.

![37](https://github.com/user-attachments/assets/d71abcfc-44d7-4947-9c08-11aeeaa3d5fd)
![38](https://github.com/user-attachments/assets/62c6b6c3-0f86-4615-888c-f9c5c6104956)

**Comment by hostcc** [comment]
> I put its MAC in DHCP Address Reservation and reserved the IP 10.10.10.250 for the G90B alarm and now it is not recognized in Home Assistant and it is slow on the cell phone

While it might be out of scope for the current issue I do remember the panel starts to timeout on WiFi if it has no Internet connection - the `10.10.10.x` subnet might be lacking NAT or alike enabled in your network configuration. Alternatively, HomeAssistant not able connecting to the panel over `10.10.10.250` might indicate missing routes between `192.168.0.x` and `10.10.10.x` subnets, or a firewall blocking connections from `192.168.0.x` to `10.10.10.x`

Anyways, 1.17.0 should give you al least sensors state change during the alarm condition.

**Comment by Gaio-Christiano** [comment]
No, the Home Assistant had IP 10.10.10.2, the modem had IP 10.10.10.1 and the G90B had IP 10.10.10.250.
I changed the IP range of the modem from the old NET to the current Claro from Arris and then reverted to the old configuration with the backup.

**Comment by hostcc** [comment]
@Gaio-Christiano , network related aspects might be tricky to resolve sometimes.

Anyways, let's capture what is going on - please do the following:
- Update the component to 1.17.0 is not done already
- I noticed redundant device for the component (due to some changes in previous versions) - please delete both and re-add the integration setting up the panel. Existing automations (if any) for the panel should remain intact (I did same for mine and it worked)
- Ensure `Simulate device alerts from history` configuration option is enabled in the configuration of the panel in Home Assistant
- Please do `Enable debug logging` on the device in Home Assistant, trigger the alarm and activate wireless door sensor a few times, then disable debug logging
- Please do `Download diagnostics` on the device in Home Assistant
- Then please attach both files here, I'll have look

Thanks in advance!

**Comment by Gaio-Christiano** [comment]
Good afternoon!
1 - Yes, the component was already in version 1.17.0, as can be seen in the image above;
2 - Since it was in a new IP network 10.10.10.0, I had to add a new one and left the old one previously added with the network 192.168.0.0;
3 - Yes, this option was enabled;
4 - I will do this on Sunday when I get home;
5 - I will do this on Sunday when I get home;

**Comment by hostcc** [comment]
Hi, @Gaio-Christiano - could you please share the latest on the issue? Is that still affecting your setup, please?

**Comment by Gaio-Christiano** [comment]
Good morning!
I haven't updated to this new version yet.
The previous one is working fine without any problems and I created some routines in Home Assistant to turn off the alarm in less time and reset it.
So I was also able to implement it by having Alexa announce the location of the alarm, send a message to Telegram and WhatsApp telling the location of the alarm.
I also programmed it to turn on two RGB lamps and depending on the color I already know where it went off in my house.

I closed it because I was afraid of updating and it stopping working lol, an update came out on Alexa that stopped Home Assistant from opening.

**Comment by Gaio-Christiano** [comment]
Good morning!
I haven't updated to this new version yet.
The previous one is working fine without any problems and I created some routines in Home Assistant to turn off the alarm in less time and reset it.
So I was also able to implement it by having Alexa announce the location of the alarm, send a message to Telegram and WhatsApp telling the location of the alarm.
I also programmed it to turn on two RGB lamps and depending on the color I already know where it went off in my house.

I was afraid of updating and it would stop working lol, an update came out for Alexa that stopped Home Assistant from opening.

**Comment by hostcc** [comment]
Thanks, @Gaio-Christiano! Happy to hear the integration is working for you - I think there were no breaking changes between 1.17.0 and 1.19.1, so you might try updating or keep the older version, whatever works best for you.

Unless there is anything pending for the issue I'm going to close it - thanks for great cooperation!
